/* Author: Jan Sucan */

#ifndef PROTOCOL_RETURN_CODES_H_
#define PROTOCOL_RETURN_CODES_H_

enum protocol_return_codes {
	PROTOCOL_OK = 0x00,
	PROTOCOL_DIRECTC_PAGE_REQUEST = 0x01,
	// Chyby protokolu
	PROTOCOL_ERROR_UNKNOWN_CMD_CODE = 0x10,
	PROTOCOL_ERROR_INCORRECT_CMD_SIZE = 0x11,
	PROTOCOL_ERROR_NO_OPERATION_IN_PROGRESS = 0x12,
    PROTOCOL_ERROR_OPERATION_IN_PROGRESS = 0x13
};

#endif /* PROTOCOL_RETURN_CODES_H_ */