/* Author: Jan Sucan */

#ifndef RETURN_CODES_H_
#define RETURN_CODES_H_

#include <limits.h>

typedef enum {
	// Privatne kody nesirene v REJ ramcoch
	FRAME_OK = 0x00,
	DATA_OK = 0x00,
	DATA_ERROR,
	FRAME_TIMEOUT,
	
	// Kody sirene v REJ ramcoch
	DATA_STARTING_HAS_NONZERO_SEQ_NUMBER = 0x10,
	DATA_RELATION_TIMEOUT,
	
	DATA_DATA_HAS_NO_PAYLOAD = 0x30,
	DATA_DATA_HAS_ACK_FLAG,
	DATA_DATA_HAS_REJ_FLAG,
	DATA_DATA_RELATION_ID_MISMATCH,
	DATA_DATA_SEQ_NUMBER_MISMATCH,
	
	DATA_ACK_HAS_PAYLOAD = 0x50,
	DATA_ACK_HAS_NOT_ACK_FLAG,
	DATA_ACK_HAS_LOR_FLAG,
	DATA_ACK_HAS_REJ_FLAG,
	DATA_ACK_RELATION_ID_MISMATCH,
	DATA_ACK_SEQ_NUMBER_MISMATCH,
	
	FRAME_RECEIVE_ERROR = 0x70,
	FRAME_BAD_HEADER_CHECKSUM,
	FRAME_BAD_DATA_CHECKSUM,
	FRAME_PROTOCOL_VERSION_MISMATCH
} yup_retcode_t;

#endif /* RETURN_CODES_H_ */